FROM node:18

ARG BOT_TOKEN
ARG SPREAD_SHEET_ID
ARG G_PRIVATE_KEY
ARG G_PRIVATE_KEY_ID

ENV BOT_TOKEN=${BOT_TOKEN}
ENV SPREAD_SHEET_ID=${SPREAD_SHEET_ID}
ENV G_PRIVATE_KEY=${G_PRIVATE_KEY}
ENV G_PRIVATE_KEY_ID=${G_PRIVATE_KEY_ID}
ENV PORT=8080

WORKDIR /app
COPY . .
RUN npm install
EXPOSE 8080
CMD [ "node", "bot.js" ]